### ISSUE TITLE
Update to fs.cos prefix key

### ISSUE THREAD

**Issue by gadamc** [ibm-watson-data-lab/ibmos2spark#19]
We should update from 's3d' schema and prefix key to 'cos'. 

https://github.com/SparkTC/stocator#stocator-and-ibm-cloud-object-storage-cos

**Comment by bassel-zeidan** [comment]
Python PR:
https://github.com/ibm-watson-data-lab/ibmos2spark/pull/22

**Comment by bassel-zeidan** [comment]
https://github.com/ibm-watson-data-lab/ibmos2spark/pull/23

**Comment by bassel-zeidan** [comment]
https://github.com/ibm-watson-data-lab/ibmos2spark/pull/24

**Comment by bassel-zeidan** [comment]
This item has been implemented. Closing this item...
