### ISSUE TITLE
CloudObjectStorage : remove iam endpoint from generated credentials

### ISSUE THREAD

**Issue by gilv** [ibm-watson-data-lab/ibmos2spark#47]
![screen shot 2017-12-19 at 13 01 55](https://user-images.githubusercontent.com/6321715/34154047-da29a846-e4bc-11e7-8e3d-e10b4f068856.png)

The credentials that generates by contains "iamServiceEndpoint". This field should be removed completely as it only confuses. IBM COS SDK already has value for IAM endpoint in production.

We can keep this value as optional, but it should not be visible as part of generated credentials

**Comment by bassel-zeidan** [comment]
Hi @gilv,

the "insert-to-code" feature is available also on the Londen deployment (not only dallas) and in London deployment, this endpoint is different on production that is why this url is being added. 

One note: this value is optional in ibmos2spark so the default iam endpoint on production dallas will be picked up if not provided by IBM sdk.
